baseURL = 'https://uktrees.com'
languageCode = 'en-us'
title = 'UK trees'
enableRobotsTXT = false

# https://gohugo.io/hugo-modules/
# https://blog.hugomods.com/posts/2023/03/how-to-use-hugo-modules/
[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'

# https://gohugo.io/content-management/markdown-attributes/
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
       [markup.goldmark.parser.attribute]
        block = true
        title = true