baseURL = 'https://uktrees.com'
languageCode = 'en-us'
title = 'UK trees'

# https://gohugo.io/content-management/markdown-attributes/
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
       [markup.goldmark.parser.attribute]
        block = true
        title = true